### ISSUE TITLE
Dead project?

### ISSUE THREAD

**Issue by rejas** [alexyak/motiondetector#10]
I don't know if you work on this anymore. So I forked your repo since if anybody wants to check it out: https://github.com/rejas/MMM-MotionDetector

Accidentally opened the issue wrongly in https://github.com/alexyak/voicecontrol/issues/10, will be closing that one.

**Comment by Wominator** [comment]
Hi rejas!,
Cool idea. Which cameras will work? I'm just playing around with an old Acer Aspire One D260. Atom CPU, 2 GiB RAM and 160 GiB HDD and Xubuntu 16.4.3 LTS. It has a buid-in webcam, which I would like to use for motion detection. I installed the module, set the timeout to 6000 for testing, covered the cam, but nothing happens. The module doesn't turn off the screen.  To doublecheck, if the camera works, I installed "Cheese" (a webcam utility) and I can take fotos and videos with the cam.
Any idea? Or will it work only with the RPi-Cam?  

Thanks in advance and regards from Berlin

wominator

**Comment by rejas** [comment]
Not sure which cameras will work, I got a ps3-usb cam working without any extra configuration neccessary. Could you open an issue in my repo (maybe add some logs from MM) and I'll take a look later?

**Comment by Wominator** [comment]
Hi again!

Thanks for the quick response. Not sure, but I can't open an issue in your repo.
What I found in the mm-out-0.log:

> magicmirror@2.1.3 start /home/wominator/MagicMirror
> sh run-start.sh

Starting MagicMirror: v2.1.3
Loading config ...
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: MMM-TextClock.
No helper found for module: currentweather.
No helper found for module: weatherforecast.
Initializing new module helper ...
Module helper loaded: calendar
Initializing new module helper ...
......
Module helper loaded: MMM-MotionDetector
All module helpers loaded.
Starting server on port 8080 ... 
Server started ...
Connecting socket for: updatenotification
Connecting socket for: calendar
Starting node helper for: calendar
Connecting socket for: MMM-PublicTransportBerlin
Connecting socket for: MMM-DWD-WarnWeather
MMM-DWD-WarnWeather helper started...
Connecting socket for: newsfeed
Starting module: newsfeed
Connecting socket for: MMM-Remote-Control
Starting node helper for: MMM-Remote-Control
Connecting socket for: MMM-MotionDetector
Sockets connected & modules started ...
monitor on: true
monitor :
Launching application.
Create new calendar fetcher for url: https://calendar.google.com/calendar/....
Create new news fetcher for url: http://www......
monitor :
Transportation fetcher for station Berlin, XYZ-Str. created. (Station ID: 90XYZ)
monitor has been deactivated
monitor :
monitor :
monitor has been deactivated
monitor :
monitor :
monitor has been deactivated
monitor :
monitor :
monitor has been deactivated
monitor :
monitor :
monitor has been deactivated
monitor :
monitor :
monitor has been deactivated
monitor :
monitor :
monitor has been deactivated
monitor :
monitor :
monitor has been deactivated
monitor :
monitor :
monitor has been deactivated
monitor :
monitor :
monitor has been deactivated
monitor :
monitor :
monitor has been deactivated
monitor :
monitor : 

It looks like, the module wants to turn of the screen, but it is switched on directly again.

Which other logs would you need?
Regards 
wominator

**Comment by rejas** [comment]
You can now add issues to my repo too :-) Hopefully I find some time to compare your logs to mine at home. Will report back then....

**Comment by Wominator** [comment]
Thanks again for the quick answer. Take your time, it's not that urgent in the moment.
Regards
wominator

**Comment by rejas** [comment]
Moved the conversation about your issue, @Wominator, to https://github.com/rejas/MMM-MotionDetector/issues/1
